var GRAPEFRUIT_LIGHT = '#F76D82';
var GRAPEFRUIT_NORMAL = '#EC5564';
var GRAPEFRUIT_DARK = '#D94452';

var BITTERSWEET_LIGHT = '#FC8370';
var BITTERSWEET_NORMAL = '#FB6D51';
var BITTERSWEET_DARK = '#E8563F';

var SUNFLOWER_LIGHT = '#FCD277';
var SUNFLOWER_NORMAL = '#FECD57';
var SUNFLOWER_DARK = '#F5BA45';

var GRASS_LIGHT = '#B4E080';
var GRASS_NORMAL = '#9ED36A';
var GRASS_DARK = '#8ACO54';

var MINT_LIGHT = '#62DDBD';
var MINT_NORMAL = '#46CEAD';
var MINT_DARK = '#35BB9B';

var AQUA_LIGHT = '#66D4F1';
var AQUA_NORMAL = '#4FC0E8';
var AQUA_DARK = '#3AADD9';

var BLUEJEANS_LIGHT = '#73B1F4';
var BLUEJEANS_NORMAL = '#5E9CEA';
var BLUEJEANS_DARK = '#4B89DA';

var LAVENDER_LIGHT = '#B3A5EF';
var LAVENDER_NORMAL = '#AC92EA';
var LAVENDER_DARK = '#967ADA';

var PANTHER_LIGHT = '#F299CE';
var PANTHER_NORMAL = '#EB87BF';
var PANTHER_DARK = '#D670AC';

var SKINTONE_LIGHT = '#F4D0B5';
var SKINTONE_NORMAL = '#F0C845';
var SKINTONE_DARK = '#E4B693';

var LIGHTGRAY_LIGHT = '#F4F6F9';
var LIGHTGRAY_NORMAL = '#E5E8EC';
var LIGHTGRAY_DARK = '#CBD0D8';

var DARKGRAY_LIGHT = '#A9B1BC';
var DARKGRAY_NORMAL = '#646C77';
var DARKGRAY_DARK = '#424953';